-- Seed the required exhibit list into Supabase.
-- This script assumes db/schema.sql has already been executed.
-- If you prefer a programmatic seed, run: npm run seed

-- Minimal SQL seed with required entities.
insert into exhibits (
  slug, name, url_original, wayback_url, successor_url,
  years_active_start, years_active_end, category, status,
  short_description, full_story, peak_visitors, country_origin,
  what_made_it_special, thumbnail_url, featured, created_at
)
select
  x.slug,
  x.name,
  x.url_original,
  x.wayback_url,
  x.successor_url,
  x.years_active_start,
  x.years_active_end,
  x.category::exhibit_category,
  x.status::exhibit_status,
  x.short_description,
  x.full_story,
  x.peak_visitors,
  x.country_origin,
  x.what_made_it_special,
  x.thumbnail_url,
  x.featured,
  now()
from (
  values
    ('geocities','GeoCities','http://www.geocities.com','https://web.archive.org/web/*/geocities.com',null,1994,2009,'Personal/GeoCities','archived','The neighborhood-based home page service that gave millions of people their first personal site.','GeoCities began in 1994 as Beverly Hills Internet and quickly became one of the most recognizable homes for personal publishing on the early web. It organized pages into themed neighborhoods, making a sprawling and chaotic internet feel like a map you could actually walk through.\n\nBy the late 1990s GeoCities represented amateur web culture at full volume: animated GIFs, MIDI music, guestbooks, and hand-coded HTML experiments everywhere. Yahoo acquired the company in 1999 for billions during the dot-com boom, turning it into a mainstream entry point for first-time creators.\n\nAs blogging platforms and social media replaced static home pages, GeoCities traffic and relevance faded. Yahoo shut the US service in 2009, though archives and preservation groups saved large portions. Today GeoCities survives as a symbol of web creativity before platform standardization.','35 million monthly visitors','United States',array['Neighborhood metaphor that organized personal pages by interest','Mass participation in hand-built web design','A visual language of GIFs, marquees, and guestbooks'],'/icons/retro-site.svg',true),
    ('napster','Napster','http://www.napster.com','https://web.archive.org/web/*/napster.com','https://www.napster.com',1999,2001,'Entertainment','reborn','Peer-to-peer file sharing giant that rewired music discovery and provoked an industry-wide legal war.','Napster launched in 1999 and made digital music sharing effortless for ordinary users. Instead of slow, scattered downloads, it offered searchable MP3 catalogs through a central index connected to user computers.\n\nUsage exploded among students and young listeners who suddenly had near-instant access to massive libraries. At the same time, labels and artists argued that uncontrolled sharing undermined copyright and collapsed existing distribution models.\n\nCourt rulings forced the original service to shut down in 2001. The name later returned through licensed services under different ownership. Napster remains one of the defining stories of internet disruption, legality, and the shift to streaming-era expectations.','26.4 million users','United States',array['Simple search-first MP3 sharing','Cultural flashpoint for digital copyright law','Changed listener expectations for instant access'],'/icons/retro-site.svg',true),
    ('altavista','AltaVista','http://www.altavista.com','https://web.archive.org/web/*/altavista.com',null,1995,2013,'Search Engines','gone','A pioneering search engine known for speed, broad indexing, and early web translation tools.','AltaVista was introduced in 1995 by Digital Equipment Corporation as a demonstration of search technology and hardware performance. It quickly gained attention because it indexed a large share of the web and delivered results fast for the era.\n\nAs the web commercialized, AltaVista tried to evolve from pure search into a portal, adding news, shopping, and other content layers. That move reflected the dominant strategy of late-1990s internet businesses, but it diluted the clean search experience that made users loyal.\n\nCompetition intensified and Google eventually dominated search through relevance and simplicity. AltaVista changed owners several times before Yahoo closed it in 2013. It is remembered as one of the first engines that made the growing web feel searchable at scale.','Around 80 million monthly users at peak era','United States',array['Large early web index','Fast query response in dial-up years','Babelfish translation became a widely known tool'],'/icons/retro-site.svg',true),
    ('ask-jeeves','Ask Jeeves','http://www.askjeeves.com','https://web.archive.org/web/*/askjeeves.com','https://www.ask.com',1997,2006,'Search Engines','reborn','Question-and-answer styled search with a butler mascot that made the web feel conversational.','Ask Jeeves launched in 1997 with a playful idea: users could type natural-language questions instead of keyword strings. The service framed search as an approachable helper experience, led by its iconic butler character.\n\nIts branded personality stood out in a crowded portal landscape, and many first-time users found the concept friendlier than technical search syntax. Over time, however, relevance quality and index breadth became decisive factors across the industry.\n\nThe company eventually rebranded toward Ask.com and retired the Jeeves character from center stage. While the original interface faded, Ask Jeeves is still remembered for normalizing conversational search behavior long before modern interfaces made it standard.','Over 40 million monthly visitors in early 2000s','United States',array['Natural-language query framing','Strong mascot-driven brand identity','Early push toward user-friendly search interaction'],'/icons/retro-site.svg',true),
    ('myspace','MySpace','http://www.myspace.com','https://web.archive.org/web/*/myspace.com','https://myspace.com',2003,null,'Social','reborn','The customizable social network where profile music, top friends, and HTML themes defined identity.','MySpace launched in 2003 and rapidly became a central hub for online social identity, especially among younger users. It allowed deep profile customization with HTML and CSS tweaks, creating a wild visual culture unlike later standardized platforms.\n\nMusic communities grew quickly, and artists used MySpace to publish tracks and build fan bases before streaming platforms became dominant. The site became a cultural marker of mid-2000s internet life, including social rituals like Top 8 rankings.\n\nAfter Facebook''s cleaner interface and broader network effects took over, MySpace lost mainstream momentum. The brand still exists in reduced form and changed strategic focus, but its original era remains one of the most influential chapters in social web history.','115 million monthly visitors (2008)','United States',array['Deep profile customization and expressive identity','Major launchpad for independent musicians','Defined social norms for an entire generation'],'/icons/retro-site.svg',true),
    ('friendster','Friendster','http://www.friendster.com','https://web.archive.org/web/*/friendster.com',null,2002,2015,'Social','gone','An early social network that introduced profile-based friend graphs to mainstream audiences.','Friendster launched in 2002 and quickly attracted users eager to map real-world friendships online. Its profile and friend-connection model strongly influenced later social platforms that would scale globally.\n\nThe service struggled with performance as demand surged, and site reliability became a long-running complaint. As alternatives improved speed and user experience, migration accelerated away from Friendster in key markets.\n\nThe company later attempted pivots, including gaming, before shutting down in 2015. Even with its decline, Friendster occupies a foundational place in social networking history as one of the first major graph-based communities.','Over 100 million registered users','United States',array['Popularized social graph mechanics','Influenced profile-driven network design','Strong early adoption in Southeast Asia'],'/icons/retro-site.svg',false),
    ('neopets','Neopets','http://www.neopets.com','https://web.archive.org/web/*/neopets.com','https://www.neopets.com',1999,null,'Gaming','reborn','Virtual pets, browser games, and a kid-safe economy made Neopets a daily ritual for millions.','Neopets started in 1999 as a virtual pet platform where users cared for digital creatures and earned currency through mini-games. It combined collection, role-play, and light economic systems in a browser-first world.\n\nIts bright visual design and frequent events helped users build long-term habits, while social features made it feel like a full online world. For many players, Neopets was both a game and an introduction to internet community norms.\n\nThough ownership and direction changed over the years, the brand endured through nostalgia and dedicated fans. Neopets remains active in successor form, showing unusual longevity for an early 2000s web game ecosystem.','35 million users by 2005','United Kingdom',array['Persistent virtual world in the browser','Accessible mini-game and economy loop','Long-running fan loyalty'],'/icons/retro-site.svg',false),
    ('homestar-runner','Homestar Runner','http://www.homestarrunner.com','https://web.archive.org/web/*/homestarrunner.com','https://homestarrunner.com',2000,null,'Entertainment','reborn','Flash-era comedy universe that thrived through animation, inside jokes, and weekly updates.','Homestar Runner emerged around 2000 as a handcrafted animation site built around recurring characters and absurd humor. During the Flash era it became one of the web''s most beloved independent comedy destinations.\n\nThe site rewarded repeat visits through serialized jokes, hidden links, and a distinct voice that spread through school labs and office desktops alike. Its Strong Bad Emails in particular shaped internet comedy cadence for a generation of fans.\n\nWhen Flash declined, the creators paused major output but later returned with selective updates. Homestar Runner still exists as a cultural artifact and active archive of a period when independent web animation could define mainstream internet humor.','Millions of weekly views in peak Flash era','United States',array['Original web-native animation style','Serialized comedy with cult fanbase','Interactive hidden jokes in site navigation'],'/icons/retro-site.svg',false),
    ('newgrounds','Newgrounds','http://www.newgrounds.com','https://web.archive.org/web/*/newgrounds.com','https://www.newgrounds.com',1995,null,'Entertainment','reborn','A creator-first portal for Flash animation and games that launched internet legends.','Newgrounds began in 1995 and became a central stage for user-submitted animation and browser games. It was one of the earliest mainstream platforms where independent creators could publish directly to a massive audience.\n\nIts ratings, community forums, and contests built a merit-driven culture that helped artists improve and get discovered. Many creators who later entered mainstream media first built followings through Newgrounds projects.\n\nDespite the decline of Flash, Newgrounds adapted and stayed online, preserving older work while supporting newer formats. It remains one of the strongest examples of durable internet community infrastructure from the early web era.','Tens of millions of monthly visitors in Flash peak','United States',array['Open publishing for indie animators and game makers','Community moderation and rating culture','Long-term preservation of Flash-era creativity'],'/icons/retro-site.svg',false),
    ('xanga','Xanga','http://www.xanga.com','https://web.archive.org/web/*/xanga.com','https://xanga.com',1999,null,'Social','reborn','Blogging-meets-social platform where journals, comments, and rings built intimate online circles.','Xanga launched in 1999 and evolved from a sharing utility into a personal publishing platform with strong social features. It was especially popular among teens and students who treated it as both diary and social feed.\n\nUsers customized layouts, posted long reflections, and built communities through comments and web rings. Compared with later short-form networks, Xanga encouraged longer personal writing and sustained interaction among regular readers.\n\nTraffic declined as newer social platforms shifted habits, and Xanga underwent ownership and product changes. The name persisted in reduced forms, but its classic era captures a moment when blogging and social identity lived in the same interface.','30+ million users in peak period','United States',array['Hybrid of blog, community, and profile','Strong culture of long-form personal posts','Comment-driven micro-communities'],'/icons/retro-site.svg',false),
    ('livejournal','LiveJournal','http://www.livejournal.com','https://web.archive.org/web/*/livejournal.com','https://www.livejournal.com',1999,null,'Forums','reborn','Community journaling platform that blended blogging, fandom, and threaded discussion culture.','LiveJournal launched in 1999 and gave users a structured way to maintain journals with privacy controls and friend lists. It quickly became an influential home for fandom, niche communities, and personal writing.\n\nUnlike many later social networks, LiveJournal emphasized posts and comment threads rather than endless algorithmic feeds. Communities formed around shared interests and often developed sophisticated moderation and posting norms.\n\nThe platform changed ownership and regional focus over time, reducing its influence in many markets. Even so, its architecture and community practices left a lasting mark on online discourse and identity formation.','Millions of active journals in the 2000s','United States',array['Journaling plus community groups','Flexible privacy controls for posts','Deep role in fandom and online subcultures'],'/icons/retro-site.svg',false),
    ('bolt','Bolt.com','http://www.bolt.com','https://web.archive.org/web/*/bolt.com',null,1996,2007,'Social','gone','A youth-focused social portal mixing profiles, chat, and forums before social media matured.','Bolt.com launched in the mid-1990s as a destination for teens and young adults seeking online community. It combined messaging, profiles, chat, and editorial content into a portal format typical of the era.\n\nAs advertising models tightened and competition increased, sustaining broad social portals became difficult. Bolt attempted redesigns and community features, but network effects shifted toward larger platforms.\n\nBy the late 2000s the site shut down, leaving only archived snapshots. Bolt is often remembered as a transitional platform between early chat communities and modern social networks.','Over 10 million registered users','United States',array['Youth-centered online community design','Portal style with social tools and media','Important bridge between chat rooms and modern social platforms'],'/icons/retro-site.svg',false),
    ('ivillage','iVillage','http://www.ivillage.com','https://web.archive.org/web/*/ivillage.com',null,1995,2018,'News & Media','gone','One of the largest online communities and content hubs focused on women and family life.','iVillage launched in 1995 and built a major audience around health, parenting, relationships, and lifestyle content. It paired editorial programming with active message boards, creating a strong community identity.\n\nDuring the portal era, iVillage stood out by focusing on audience needs that were often underserved elsewhere. The brand expanded through partnerships and acquisitions as digital media models evolved through the 2000s.\n\nAfter changes in ownership and strategy, iVillage eventually shut down as a standalone destination. Its influence persists in the modern blend of niche content verticals with community discussion features.','30 million monthly uniques at peak','United States',array['Focused community and editorial voice','Strong forum participation around life topics','Pioneered targeted digital media verticals'],'/icons/retro-site.svg',false),
    ('excite','Excite','http://www.excite.com','https://web.archive.org/web/*/excite.com','https://www.excite.com',1994,null,'Search Engines','reborn','Search-to-portal heavyweight that helped define homepage culture in the late 1990s.','Excite started in 1994 as a search technology company and quickly expanded into a major portal destination. For many users, Excite became the front door to news, email, search, and daily web browsing.\n\nIts growth reflected the period when portals competed to keep users inside broad ecosystems. Mergers and strategic bets during the dot-com years made the company a visible player, though the market eventually shifted toward specialist services and cleaner search-first experiences.\n\nThe Excite brand survived through later transitions and remains online in successor forms. Its peak years represent the moment when portal homepages tried to be the internet in one page.','Tens of millions monthly at portal peak','United States',array['Early blend of search, media, and communication tools','Highly recognizable portal homepage format','Major presence during first internet boom'],'/icons/retro-site.svg',false),
    ('lycos','Lycos','http://www.lycos.com','https://web.archive.org/web/*/lycos.com','https://www.lycos.com',1994,null,'Search Engines','reborn','A foundational search and portal brand that evolved through several internet business eras.','Lycos was created in 1994 from a Carnegie Mellon research project and became one of the web''s earliest popular search engines. It expanded rapidly as internet usage grew and portal strategies became dominant.\n\nThe brand added mail, hosting, and media features to compete in homepage wars. Corporate ownership changed several times, mirroring the volatility of early internet consolidation and international expansion.\n\nWhile no longer central to everyday browsing, Lycos still exists and remains historically significant. It demonstrates how academic search research became commercial infrastructure for the public web.','Up to 50 million monthly visitors in late 1990s','United States',array['University research roots in web search','Major early portal expansion','Long-lived brand through multiple market cycles'],'/icons/retro-site.svg',false),
    ('theglobe','TheGlobe.com','http://www.theglobe.com','https://web.archive.org/web/*/theglobe.com',null,1995,2008,'Social','gone','Early social networking experiment famous for one of the dot-com era''s wildest IPO stories.','TheGlobe.com launched in 1995 with a focus on community spaces, personal publishing, and online interaction. It gave users tools to join interest groups and build identity before social networking had settled into familiar formats.\n\nThe company became famous during the dot-com boom for a dramatic IPO surge that symbolized market hype around internet startups. Underneath that spectacle, it still represented real experimentation in large-scale user communities.\n\nAs the bubble burst and competition intensified, the platform''s influence declined and operations changed course. The site eventually disappeared as a major destination, but its story remains a cautionary and iconic chapter of early web economics.','Millions of registered community members','United States',array['Very early social community model','Landmark dot-com IPO moment','Precursor to profile and group-based web interaction'],'/icons/retro-site.svg',false),
    ('deja-news','Deja News','http://www.dejanews.com','https://web.archive.org/web/*/dejanews.com','https://groups.google.com',1995,2001,'Forums','reborn','Usenet search and archive service that made decades of online discussion discoverable.','Deja News launched in 1995 and indexed Usenet postings, making distributed discussion archives searchable from the web. This transformed a vast text ecosystem into something casual users could navigate.\n\nResearchers, hobbyists, and journalists used Deja News to trace conversations and technical advice across years of posts. It acted as both a discovery engine and a memory layer for early online culture.\n\nGoogle acquired the archive in 2001 and integrated it into Google Groups. Deja News disappeared as a standalone brand, but its preservation mission lived on through successor infrastructure.','One of the largest searchable Usenet indexes','United States',array['Searchable archive of Usenet discussions','Preserved long-tail technical and cultural knowledge','Bridge between pre-web and web-era communities'],'/icons/retro-site.svg',false),
    ('mp3com','MP3.com','http://www.mp3.com','https://web.archive.org/web/*/mp3.com',null,1997,2003,'Entertainment','gone','A massive early destination for legal digital music distribution and indie artist discovery.','MP3.com launched in 1997 as a hub for digital music listening, downloads, and independent artist exposure. It helped normalize the idea that music careers could begin on the open web without traditional label pathways.\n\nThe platform offered tools for artists and became a high-traffic destination during the transition from CDs to digital files. Legal battles around specific services and licensing complicated its trajectory during a turbulent period for music rights online.\n\nAfter acquisitions and strategic changes, MP3.com faded as a core destination and eventually shut down in its original form. Its legacy survives in the independent distribution culture that became standard in later music platforms.','Roughly 10 million unique monthly visitors','United States',array['Indie artist distribution at scale','Mainstreamed web-native music discovery','Early test case for online music rights conflict'],'/icons/retro-site.svg',false),
    ('kazaa','Kazaa','http://www.kazaa.com','https://web.archive.org/web/*/kazaa.com',null,2001,2012,'Entertainment','gone','Post-Napster peer-to-peer giant known for massive scale and controversial file-sharing culture.','Kazaa rose in the early 2000s as one of the largest peer-to-peer file sharing networks after Napster''s shutdown. It supported decentralized exchange of music and other media files at huge volume.\n\nFor users, Kazaa offered convenience and breadth; for rights holders, it represented a continuation of unauthorized distribution problems. The platform also became associated with security concerns, including bundled adware and malware risks in some versions.\n\nLegal pressure and market shifts eventually ended Kazaa''s original role in internet culture. It remains part of the broader story of how media consumption habits changed faster than licensing and platform governance.','Hundreds of millions of downloads of client software','Netherlands',array['Massive decentralized sharing network','Key successor to Napster-era behavior','Critical chapter in digital media legality debates'],'/icons/retro-site.svg',false),
    ('angelfire','Angelfire','http://www.angelfire.com','https://web.archive.org/web/*/angelfire.com','https://www.angelfire.com',1996,null,'Personal/GeoCities','reborn','One of the classic free web hosting homes for personal pages, fandom shrines, and niche guides.','Angelfire launched in 1996 and offered free hosting tools that brought amateur site creation to wide audiences. Along with peers like GeoCities, it became a canvas for personal expression in the pre-social era.\n\nUsers built fan pages, tutorials, diaries, and tightly focused hobby archives with minimal barriers to entry. The platform''s DIY spirit helped establish norms for linking, attribution, and niche community knowledge sharing.\n\nThough no longer central to internet culture, Angelfire survives in reduced form and through extensive archives. Its enduring value is historical: a record of web publishing before templates and feeds flattened personal style.','Millions of hosted pages','United States',array['Free personal hosting for non-technical users','Strong long-tail niche and fandom archives','Iconic raw HTML aesthetic'],'/icons/retro-site.svg',true)
) as x(
  slug, name, url_original, wayback_url, successor_url,
  years_active_start, years_active_end, category, status,
  short_description, full_story, peak_visitors, country_origin,
  what_made_it_special, thumbnail_url, featured
)
on conflict (slug) do update set
  name = excluded.name,
  url_original = excluded.url_original,
  wayback_url = excluded.wayback_url,
  successor_url = excluded.successor_url,
  years_active_start = excluded.years_active_start,
  years_active_end = excluded.years_active_end,
  category = excluded.category,
  status = excluded.status,
  short_description = excluded.short_description,
  full_story = excluded.full_story,
  peak_visitors = excluded.peak_visitors,
  country_origin = excluded.country_origin,
  what_made_it_special = excluded.what_made_it_special,
  thumbnail_url = excluded.thumbnail_url,
  featured = excluded.featured;
